[BE] 프로필 페이지 - 프로필 페이지 API
boostcampwm-2021/web32-SSUL pull request #113
Opened 2021-11-15 15:43 UTC by ChanYangYu

## 관련 이슈

- closes #72

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무

## 작업 요약
> 작업 내역 요약
- 유저 프로필 자기소개 GET API 구현
- 유저 프로필 자기소개 PATCH API 구현
- 유저 프로필 기술스택 GET API 구현
- 유저 프로필 기술스택 PUT API 구현 
- 유저 프로필 활동내역  GET API 구현
- 멘토 신청 POST API 구현
- 유저 멘토링 기술스택 GET API 구현
## Preview

> 선택 사항

- 유저 프로필 자기소개 PATCH API 
![image](https://user-images.githubusercontent.com/55623688/141809194-4fdba634-66ce-4c0e-b968-555e265e3d9a.png)

- 유저 프로필 자기소개 GET API 
![image](https://user-images.githubusercontent.com/55623688/141809260-daeccdfe-0d67-493c-9fdd-766cb3620996.png)

- 유저 프로필 활동내역  GET API
![image](https://user-images.githubusercontent.com/55623688/141808522-08e868c2-febd-47fd-8659-c684231802b6.png)

- 유저 프로필 기술스택 PUT API
![image](https://user-images.githubusercontent.com/55623688/141809830-1fd605cd-10fd-4a82-886b-427a6a2a5c3c.png)

- 유저 프로필 기술스택 GET API
![image](https://user-images.githubusercontent.com/55623688/141810021-9230fc80-aa96-490a-b0aa-51f5ef026f38.png)

- 유저 멘토링 기술스택 GET API
![image](https://user-images.githubusercontent.com/55623688/141809544-00a48dc3-53ce-4e3b-a3a4-5b48f54e1649.png)

- 멘토 신청 POST API 
![image](https://user-images.githubusercontent.com/55623688/141810327-84927cfd-0fa3-4a3e-802e-7993f1eb2cad.png)

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 일단 Swagger로 테스트해본 부분을 보고 리뷰를 해주시면 좋을것 같습니다!
- 해당 부분은 추후에 프론트엔드 부분이 다 만들어지고 변경되어야할 로직이 있을 경우 Fix로 다시 issue를 생성하여 보완작업할  계획이라 리뷰하실 때 큼직큼직하게 문제가 있는 부분만 검토해주시면 감사하겠습니다!😁

2021-11-15 15:49 UTC, who-is-hu commented on server/src/domains/group/dto/CreateGroupDto.ts
> +  toGroup(category: Category){
toEntity 어때요?

2021-11-15 15:50 UTC, who-is-hu commented on server/src/domains/group/dto/GroupActivityDto.ts
> +  @IsDate()
여기는 DateString 안해도 괜찮은 부분인가요?

2021-11-15 15:56 UTC, who-is-hu commented on server/src/domains/group/repository/GroupRepository.ts
> +  public async findEndGroupByUserId(userId: number){
저는 복잡하지 않은 문법은 쿼리빌더 말고 그냥 find로 하는게 더 깔끔한거 같은데
한번 고려해주세요~

2021-11-15 15:57 UTC, ChanYangYu commented on server/src/domains/group/dto/GroupActivityDto.ts
> +  @IsDate()
헛.. 여기도 있었군요! 적용하겠습니다!

2021-11-15 15:57 UTC, who-is-hu commented on server/src/domains/mentoring/api/MentoringController.ts
> +    private readonly usingTechStackService: UsingTechStackService,
이거 `@Inject` 안해줘도 되나요? 근데 되고 일관성있게 넣는게 좋을 것 같습니당.

2021-11-15 15:59 UTC, who-is-hu commented on server/src/domains/mentoring/service/MentorService.ts
> +    const mentor: Mentor = new Mentor();
요거 `mentorRepository.create` 사용하면 더 못줄이나요?

2021-11-15 16:02 UTC, who-is-hu requested changes
간단한 쿼리는 쿼리빌더 안쓰는거 한번 고려해보는것도 좋을 것 같습니당.
몇 가지 오류가 있을수있다고 생각하는곳에 싱글커멘트 달아놨습니다 한번 확인해주세요~

2021-11-15 16:05 UTC, ChanYangYu commented on server/src/domains/mentoring/api/MentoringController.ts
> +    private readonly usingTechStackService: UsingTechStackService,
빠뜨린부분이 많네요 ㅋㅋㅋ 디테일한 부분까지 감사합니다~

2021-11-15 16:06 UTC, ChanYangYu commented on server/src/domains/group/repository/GroupRepository.ts
> +  public async findEndGroupByUserId(userId: number){
한번 시도해볼게요!

2021-11-15 16:13 UTC, ChanYangYu commented on server/src/domains/mentoring/service/MentorService.ts
> +    const mentor: Mentor = new Mentor();
```typescript
public async createMentor(userId: number) {
    const mentor: Mentor = this.mentorRepository.create({userId:userId});
    return await this.mentorRepository.save(mentor);
  }
```
피드백 주신방법대로 이렇게 줄여봤습니다!

2021-11-15 16:14 UTC, ChanYangYu commented on server/src/domains/group/dto/CreateGroupDto.ts
> +  toGroup(category: Category){
적용했습니다!

2021-11-16 01:39 UTC, yuchanleeme approved these changes
구현하시느라 수고하셨습니다!! LGTM~~

2021-11-16 04:53 UTC, who-is-hu approved these changes

2021-11-16 05:06 UTC, merged