[BE] 스터디룸 페이지 - 그룹 게시판 관련 API
boostcampwm-2021/web32-SSUL pull request #166
Opened 2021-11-22 12:23 UTC by Donggggg

## 관련 이슈

- closes #112 

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무
- [x] test 통과 여부

## 작업 요약
> 작업 내역 요약
- 그룹 게시글 조회 API 구현
- 그룹 게시글 작성 API 구현
- 그룹 게시글 수정 API 구현
- 그룹 게시글 삭제 API 구현
- 그룹 게시글 조회수 업데이트 API 구현 (진행중)

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- FindOrFail 함수의 에러가 하나로 통일되어 클라이언트에서 에러의 의미를 적절히 담지 못해 우선 커스텀 에러 버전으로 설정했습니다.
- FindOrFail을 사용하면 코드가 짧아지는 대신 에러 코드의 의미가 정확하지 못합니다.
- 직접 검사를 하면 코드가 약간 길어지는 대신 에러 코드의 의미가 정확합니다.
- **두 가지 방식 중 어떤 방법이 좋을지 의견 부탁드려요..!**

2021-11-22 14:33 UTC, ChanYangYu commented on server/src/domains/group/dto/groupDto.ts
> +  @IsNumber({ allowNaN: false })
여기서 allowNaN 해주는 이유가 무엇인가요??

2021-11-22 15:32 UTC, ChanYangYu approved these changes
제 생각으로는 클라이언트에서 정상적으로 값을 보낼 경우 findOrFail에서 에러가 나는 경우는 없는것으로 보이며 만약 에러가 난다면 클라이언트 이외 다른 환경에서 보내는 요청에 의해 발생한다고 생각합니다. 따라서 클라이언트 외 의도에 맞지 않는 사용자들을 위해 에러코드를 섬세하게 만들어줄 필요는 없다고 생각했습니다!

2021-11-23 01:54 UTC, Donggggg commented on server/src/domains/group/dto/groupDto.ts
> +  @IsNumber({ allowNaN: false })
원래 파라미터로 들어오는 값이 숫자가 아닐 때 Bad Request를 위해 작성했는데 다시 테스트해보니 해당 옵션이 없어도 예외 처리가 가능하네요!

2021-11-23 01:57 UTC, who-is-hu commented on server/src/domains/group/models/Post.ts
> +  type: PostType | string;
이게 되네!!

2021-11-23 02:03 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +  @ResponseSchema(PostDto, { isArray: true })
이거 응답에만 쓰는 DTO 면 PostResponse으로 이름 바꾸는거 어떨까요
앞으로 이렇게 규칙 적으면 덜 헷갈릴거같아요

2021-11-23 02:09 UTC, who-is-hu commented on server/src/domains/group/dto/PostDto.ts
> +
파일 분리하는게 좋을것 같아요

2021-11-23 02:13 UTC, who-is-hu commented
PostController 분리해도 되지 않을까요? 덩치가 꽤있는데

2021-11-23 02:18 UTC, Donggggg commented on server/src/domains/group/api/GroupController.ts
> +  @ResponseSchema(PostDto, { isArray: true })
굉장히 좋습니다..
이 PR을 기점으로 변경하고
기존 사항은 추후에 리팩토링해봅시다..

2021-11-23 02:19 UTC, Donggggg commented on server/src/domains/group/dto/PostDto.ts
> +
내부에 뭉치로 작성된 Dto를 하나의 Dto 파일로 분리하는게 좋을까요?

2021-11-23 02:20 UTC, Donggggg commented
PostController 분리를 한다면 group 도메인의 하위에 속해있어야 할까요 아니면 도메인도 분리를 하는게 좋을까요?

2021-11-23 02:22 UTC, who-is-hu commented
저는 도메인 분리해도 될것같아요

2021-11-23 03:35 UTC, yuchanleeme approved these changes
저도 찬양님 의견이랑 동일하게 서비스 외부에서 들어오는 요청에 대해 자세하게 어떤에러인지 알려줄 필요는 없다고 생각합니다!! 개발중에 클라이언트에서 description을 이용하거나 할 때만 custom 에러로 잡아주는게 좋다고 생각합니다!!

2021-11-23 03:35 UTC, yuchanleeme commented on server/src/domains/group/service/PostService.ts
> +    this.postRepository.increaseHit(post);
여기도 DB 업데이트 하기때문에 await 추가해주시면 좋을 것 같습니다!!

2021-11-23 04:10 UTC, who-is-hu commented
> 여기도 DB 업데이트 하기때문에 await 추가해주시면 좋을 것 같습니다!!

@yuchanleeme 
이런 중요한것들은 approve 하지말고 change request 하는게 실수예방에 좋을 것 같아유

2021-11-23 04:11 UTC, yuchanleeme commented
> > 여기도 DB 업데이트 하기때문에 await 추가해주시면 좋을 것 같습니다!!
> 
> @yuchanleeme 
> 이런 중요한것들은 approve 하지말고 change request 하는게 실수예방에 좋을 것 같아유

아 그렇네요!! 변경 해놓겠습니다~~ 감사합니다!!

2021-11-23 04:13 UTC, yuchanleeme requested changes

2021-11-23 04:13 UTC, yuchanleeme commented on server/src/domains/group/service/PostService.ts
> +    this.postRepository.increaseHit(post);
여기도 DB 업데이트 하기때문에 await 추가해주시면 좋을 것 같습니다!!

2021-11-23 05:27 UTC, Donggggg commented on server/src/domains/group/service/PostService.ts
> +    this.postRepository.increaseHit(post);
조회수 증가 로직이라서 쿼리 결과를 대기할 필요가 없다고 생각했는데 대기하지 않아도 await을 넣어야할까요?!

2021-11-23 06:51 UTC, yuchanleeme commented on server/src/domains/group/service/PostService.ts
> +    this.postRepository.increaseHit(post);
아하.. 전 조회수가 증가 하는 로직도 DB에 접근하는 로직이기 때문에 await를 쓰는게 맞다고 생각했습니다...! 이 부분은 조금 고민이 필요한것 같습니다!! 추후에 더 찾아보고 의논해봐도 좋을 주제 같습니다!! 일단 지금 현상태 코드로 이해하겠습니다!!

2021-11-23 06:51 UTC, yuchanleeme approved these changes
고생많으셨습니다~~!! 👍👍

2021-11-23 06:54 UTC, merged