[FE]스터디룸 그룹장 페이지 - 그룹 정보 및 참가요청 폼 구현
boostcampwm-2021/web32-SSUL pull request #182
Opened 2021-11-24 05:08 UTC by ChanYangYu

## 관련 이슈

- closes #174

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message 발생 유/무
- [X] Coding Convention 준수 유/무
- [X] test 통과 여부

## 작업 요약
> 작업 내역 요약
- 그룹장 페이지 전체 기능 구현
## Preview

> 선택 사항

https://user-images.githubusercontent.com/55623688/143178124-cbff725f-6cb6-4035-9b4e-b5fd0e1e9cd9.mp4

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 프론트엔드 테스트 코드는 추후에 test 이슈를 하나파서 바로 작성하겠습니다!
- 그룹장 페이지의 백엔드 코드는 현재 다 작성했지만 백엔드 테스트 코드와 같이 작성해서 올리겠습니다!

2021-11-24 18:22 UTC, Donggggg approved these changes

2021-11-24 18:22 UTC, Donggggg commented on client/src/api/groupHttpClient.ts
> +
해당 통신 함수들이 데이터를 수정하는 것이라면 `update{데이터명}`이 되면 더 시맨틱할 것 같네용!

2021-11-24 18:22 UTC, Donggggg commented on client/src/components/DatePicker/index.tsx
>      const now = new Date();
DatePicker가 2회 이상 사용돼서 컴포넌트로 분리했군요. 좋습니다!!

2021-11-25 16:50 UTC, yuchanleeme requested changes

2021-11-25 16:50 UTC, yuchanleeme commented on client/src/pages/GroupOwnerPage/groupInfoBox/GroupIntro.tsx
> +  const textInput = useRef<HTMLTextAreaElement>(null);
이 부분은 useState로 관리해도 좋을것 같아요!!

2021-11-25 16:50 UTC, yuchanleeme commented on client/src/pages/GroupOwnerPage/groupInfoBox/GroupTitle.tsx
> +  const textInput = useRef<HTMLTextAreaElement>(null);
여기도 useState로 관리하면 좋을것 같아요!!

2021-11-25 16:53 UTC, Donggggg commented on client/src/pages/GroupOwnerPage/groupInfoBox/GroupIntro.tsx
> +  const textInput = useRef<HTMLTextAreaElement>(null);
input의 value가 변경될 때 마다 렌더링이 안되는 것을 위해 ref를 사용하셨다면  
input을 ref로 관리하지 않고 useRef로 input의 value값을 관리하면 좋을 것 같아요.

2021-11-26 08:41 UTC, yuchanleeme approved these changes
참가요청 폼 구현 수고 많으셨습니다!! 👍

2021-11-26 08:42 UTC, ChanYangYu commented on client/src/pages/GroupOwnerPage/groupInfoBox/GroupIntro.tsx
> +  const textInput = useRef<HTMLTextAreaElement>(null);
useRef 변수로 사용하도록 코드 변경했습니다!

2021-11-26 08:42 UTC, ChanYangYu commented on client/src/pages/GroupOwnerPage/groupInfoBox/GroupTitle.tsx
> +  const textInput = useRef<HTMLTextAreaElement>(null);
코드 변경완료했습니다!

2021-11-26 08:52 UTC, ChanYangYu commented on client/src/api/groupHttpClient.ts
> +
오 그러네요! 해당 피드백 적용했습니다!

2021-11-26 16:56 UTC, merged