[BE]스터디룸 그룹장 페이지 - API 구현
boostcampwm-2021/web32-SSUL pull request #195
Opened 2021-11-25 17:07 UTC by ChanYangYu

## 관련 이슈

- closes #169

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무
- [ ] test 통과 여부

## 작업 요약
> 작업 내역 요약

- 그룹장 페이지 전체 API 구현
- 백엔드 API 테스트 코드 작성
## Preview

> 선택 사항

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 현재 기능구현은 완료했고 테스트 코드 빠르게 작성중에 있습니다. 테스트 코드가 작성이 마무리될 때까지 기능 먼저 리뷰 해주시면 감사하겠습니다~

2021-11-25 17:20 UTC, Donggggg requested changes

2021-11-25 17:20 UTC, Donggggg commented on server/src/domains/group/api/GroupOwnerController.ts
> +    return await this.groupOwnerService.getGroupInfoByGroupId(groupId);
파라미터 유효성 검증이 필요할 것 같아요!

2021-11-25 17:20 UTC, Donggggg commented on server/src/domains/group/repository/ApplyGroupRepository.ts
> +}
레포지토리 문법으로 변경할 수 있는 쿼리 같습니다!

2021-11-25 17:20 UTC, Donggggg commented on server/src/domains/group/service/GroupOwnerService.ts
> +  }
groupService에 해당 역할을 하는 서비스가 존재하는데 재사용하면 좋을 것 같아요!

2021-11-25 17:20 UTC, Donggggg commented on server/src/domains/group/service/GroupOwnerService.ts
> +    }
`!applyGroup` 은 어떤가요?!

2021-11-25 17:20 UTC, Donggggg commented on server/src/domains/group/service/GroupOwnerService.ts
> +    }
75번 라인도요!

2021-11-25 17:59 UTC, ChanYangYu commented on server/src/domains/group/api/GroupOwnerController.ts
> +    return await this.groupOwnerService.getGroupInfoByGroupId(groupId);
추가했습니다~

2021-11-25 18:00 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +  }
해당 코드 재사용하도록 코드 변경했습니다!

2021-11-26 03:06 UTC, ChanYangYu commented on server/src/domains/group/repository/ApplyGroupRepository.ts
> +}
@Donggggg  적용완료했습니다!

2021-11-26 03:06 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    }
피드백 적용완료했습니다!

2021-11-26 12:57 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const { name, intro, startAt, endAt } = await this.groupRepository.findOneOrFailByGroupId(gid);
이거 좀 고민이긴한데 이렇게하면 편하긴한데 dto에 준일님이 말해줬던 assgin 써서 옮기면
```
const group = await this.groupRepository.findOneOrFailByGroupId(gid);
return SimpleGroupInfoResponse.from(group);
```
하면 훨씬 읽기 좋긴하거든요 만약 여러곳에서 이 dto쓴다하면 `{ name, intro, startAt, endAt }` 이코드가 서비스 로직에 계속 등장해서 안좋을 것 같아요

2021-11-26 12:58 UTC, who-is-hu commented on server/src/domains/group/repository/ApplyGroupRepository.ts
> +  public findByGroupIdAndState(gid: number, state: string) {
findOneBy

2021-11-26 13:00 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const applyGroupList = await this.applyGroupRepository.findByGroupIdAndState(gid, 'PENDING');
'PENDING' 대신 만들어둔 enum 을 쓰는게 좋을 것 같습니다.

2021-11-26 13:00 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +      return {
이것도 dto에 from 메서드 만들고 하면 한줄로 줄여서 서비스 로직 간단하게 할 수 있을 것 같습니다.

2021-11-26 13:06 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    applyGroup.state = ApplyGroupState.ACCEPTED;
이 줄도 트랜잭션에 포함되어야 할 것 같습니다.

2021-11-26 13:08 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const applyGroup = await this.applyGroupRepository.findOneByIdAndOwnerId(applyId, ownerId);
GroupApply를 찾는거면 이미 pk가 있는데 ownerId가 같이 필요한 이유가 있을까요?

2021-11-26 13:08 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    if (!applyGroup) {
findOrFail 쓰면 안되는 곳인가요?

2021-11-26 13:09 UTC, who-is-hu commented on server/src/domains/group/repository/GroupRepository.ts
> +  public findOneOrFailByGroupId(groupId: number){
pk 조회니까 그냥 findOneorFailById 아닐까요

2021-11-26 13:10 UTC, who-is-hu commented on server/src/domains/group/repository/ApplyGroupRepository.ts
> +  public findOneByIdAndOwnerId(id: number, ownerId: number) {
서비스 로직에도 코멘트 달았는데 ownerId 가 왜필요한지 모르겠습니다.

2021-11-26 13:10 UTC, who-is-hu commented on server/src/domains/group/dto/UpdateGroupDto.ts
> +  name: string;
글자수 제한 박아야하지않나요?

2021-11-26 13:10 UTC, who-is-hu commented on server/src/domains/group/dto/UpdateGroupDto.ts
> +  intro: string;
글자수 제한 박아야하지않나요?

2021-11-26 13:11 UTC, who-is-hu commented on server/src/domains/group/api/GroupOwnerController.ts
> +    console.log(aid);
delete!

2021-11-26 13:14 UTC, who-is-hu commented on server/src/domains/group/dto/ApplyGroupDto.ts
> +export class ApplyParam {
위의 ApplyGroupDto와 무조건 같이 쓰이는 Param validation이 아니라
별도의 파일로 분리하는게 좋을거 같습니다

2021-11-26 13:15 UTC, who-is-hu commented on server/src/domains/group/dto/UpdateGroupDto.ts
> +export class UpdateGroupNameDto {
파일 분리하고 폴더로 묶는게 날것같습니다.

2021-11-26 13:16 UTC, who-is-hu commented on server/src/domains/group/api/GroupOwnerController.ts
> +import { GroupParam } from '../dto/groupDto';
예도 불필요하게 묶여있는거 같은데 주말에 분리합시당

2021-11-26 13:19 UTC, who-is-hu commented
테스트 여부에 체크가 안되어있는데 로컬에서 테스트 돌리면 패스 못하나요?
그럼 통과하게 고쳐서 올리면 좋을 것 같습니다.

2021-11-26 13:25 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const { name, intro, startAt, endAt } = await this.groupRepository.findOneOrFailByGroupId(gid);
오 적용시켰습니다!

2021-11-26 13:27 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const applyGroupList = await this.applyGroupRepository.findByGroupIdAndState(gid, 'PENDING');
예스! 적용완료했습니다!

2021-11-26 13:32 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +      return {
이부분도 적용완료했습니다!

2021-11-26 13:33 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    applyGroup.state = ApplyGroupState.ACCEPTED;
아 save를 나중에 하는데 바로 디비에 적용이 되는건가요??

2021-11-26 13:35 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    applyGroup.state = ApplyGroupState.ACCEPTED;
ㅇㅎ 그러네요 리팩토링때 함 실험해보고 정합시당

2021-11-26 13:38 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const applyGroup = await this.applyGroupRepository.findOneByIdAndOwnerId(applyId, ownerId);
아 이부분은 로직과 관련있는데 그냥 applyId만 비교하게 되면 
로그인한 다른 유저가 applyId를 알고있으면 
`api/group-owner/accept/1` 요청을 보내 그룹 참여 수락으로 바꿔버리는 문제가 있어
로그인 한 유저가 그룹장인지 체크를 하려고 저렇게 로직을 처리했습니다!

2021-11-26 13:40 UTC, ChanYangYu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    if (!applyGroup) {
앞의 이유 때문에 이렇게 처리했습니다!

2021-11-26 13:41 UTC, ChanYangYu commented on server/src/domains/group/repository/GroupRepository.ts
> +  public findOneOrFailByGroupId(groupId: number){
오 그러네요!

2021-11-26 13:48 UTC, ChanYangYu commented on server/src/domains/group/dto/UpdateGroupDto.ts
> +  intro: string;
적용완료했습니다!

2021-11-26 13:48 UTC, ChanYangYu commented on server/src/domains/group/dto/UpdateGroupDto.ts
> +  name: string;
적용완료했습니다!

2021-11-26 13:48 UTC, ChanYangYu commented on server/src/domains/group/api/GroupOwnerController.ts
> +    console.log(aid);
오 이거 고민했었는데 바꿔야겠네요!

2021-11-26 13:51 UTC, ChanYangYu commented on server/src/domains/group/dto/UpdateGroupDto.ts
> +export class UpdateGroupNameDto {
넵!

2021-11-26 13:55 UTC, who-is-hu commented on server/src/domains/group/api/GroupOwnerController.ts
> +    console.log(aid);
아녀 console.log지워주세요  ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-11-26 13:55 UTC, ChanYangYu commented on server/src/domains/group/api/GroupOwnerController.ts
> +import { GroupParam } from '../dto/groupDto';
넵 리팩토링이 필요해보이네요!

2021-11-26 13:59 UTC, ChanYangYu commented on server/src/domains/group/dto/ApplyGroupDto.ts
> +export class ApplyParam {
분리했습니다!

2021-11-26 14:01 UTC, ChanYangYu commented on server/src/domains/group/api/GroupOwnerController.ts
> +    console.log(aid);
앗ㅋㅋㅋㅋ 삭제하겠습니다!

2021-11-26 14:03 UTC, who-is-hu commented on server/src/domains/group/service/GroupOwnerService.ts
> +    const applyGroup = await this.applyGroupRepository.findOneByIdAndOwnerId(applyId, ownerId);
그래도 ApplyGroup을 찾는 함수에 ownerId 가 들어가는 이유는 안되는것같아요, 찾는건 이미 pk하나로만 식별해서 찾을 수 있습니다. 조인을 해서 가져오고 서비스 로직에서 검사를 하는게 맞는것 같아요.

이건 참고로 조인한 값의 어트리뷰트를 찾는경우 네이밍을 `findOneByIdAndGroupOwnerId` 이런식으로 한답니다.

2021-11-26 14:57 UTC, who-is-hu commented on server/src/domains/group/repository/GroupRepository.ts
> +    return this.findOneOrFail({ id });
findOneOrFail(id) 아닌가요?

2021-11-26 15:01 UTC, who-is-hu approved these changes

2021-11-26 15:14 UTC, yuchanleeme approved these changes
다른분들이 의견을 많이 남겨주셔서 저는 수정된 코드만 봤을 때 괜찮다고 생각합니다!! 굿굿!!

2021-11-26 16:51 UTC, Donggggg approved these changes

2021-11-26 16:54 UTC, merged