[BE] 알림 기능 API 구현
boostcampwm-2021/web32-SSUL pull request #210
Opened 2021-11-27 10:51 UTC by Donggggg

## 관련 이슈

- closes #207 

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무
- [x] test 통과 여부

## 작업 요약
> 작업 내역 요약
- 알림 전체 조회 API를 구현한다.
- 알림 읽음 처리 API를 구현한다.
- 알림 삭제 API를 구현한다.
- 알림 추가 서비스 로직을 구현한다.
- 관련 테스트 코드 작성
- 케이스에 맞는 알림 서비스 로직을 추가한다.

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 알림 서비스 로직 추가가 총 6개 케이스가 있는데 4개를 완료 했습니다.
1. 그룹 참가 요청 (완)
2. 그룹 참가 승인 (완)
3. 그룹 참가 거절 (완)
4. 멘토링 요청  (미완, 아직 완성되지 않은 API라서 구현하신 분이 추가해야할 것 같아요.)
5. 멘토링 수락 (완)
6. 멘토링 거절 (미완, 로직이 복잡해 구현하신 분이 추가해야할 것 같아요.)

2021-11-27 13:52 UTC, yuchanleeme approved these changes
alarm 추가하는 로직 파악했습니다!! merge 되면 제가 맡은 기능에 알람 로직 추가하도록 하겠습니다~~

2021-11-27 13:52 UTC, yuchanleeme commented on server/src/domains/mentoring/api/MentoringController.ts
> +    await this.alarmService.postAlarm(AlarmDto.fromGroup(group, AlarmType.MENTORING_ACCEPTED));
이런식으로 작성하면 되는군요!! 참고해서 merge 되면 작성해놓겠습니다~~!!

2021-11-27 13:56 UTC, who-is-hu commented on server/src/domains/alarm/dto/AlarmParams.ts
> +  aid: number;
alarmId

2021-11-27 14:01 UTC, who-is-hu commented on server/src/domains/alarm/repository/AlarmRepository.ts
> +  public checkReceiver(alarmId: number, receiverId: number) {
없을떄 의도적으로 에러 발생시키려고 만든 함수같은데 엔티티를 가져온다는 레이어의 역할과 안맞는것 같습니다. 에러의 검출은 서비스로직에 구현하는게 좋을 것 같아요

2021-11-27 14:04 UTC, who-is-hu commented on server/src/domains/alarm/repository/AlarmRepository.ts
> +  public checkReceiver(alarmId: number, receiverId: number) {
`existByReceiverId` 로 바꾸고 `boolean`값을 리턴하는게 낫겠네요
에러 검출은 서비스로직에서 하는게 좋을 것 같습니다.

2021-11-27 14:08 UTC, who-is-hu requested changes
checkReceiver 만 수정하면 될것 같습니다.!

2021-11-28 05:13 UTC, who-is-hu approved these changes

2021-11-28 05:15 UTC, merged