[FE] 참여 그룹 페이지
boostcampwm-2021/web32-SSUL pull request #214
Opened 2021-11-27 14:20 UTC by who-is-hu

## 관련 이슈

- closes #188 

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message 발생 유/무
- [ ] Coding Convention 준수 유/무
- [ ] test 통과 여부

## 작업 요약
> 작업 내역 요약

물음표 살인마 부탁드립니다. 

## Preview

> 선택 사항
![image](https://user-images.githubusercontent.com/6914465/143685279-43209533-72a1-4ab1-a82a-c9c39fd87ffc.png)

![image](https://user-images.githubusercontent.com/6914465/143685287-3ef7dc3d-4cdd-46a2-9a82-f71be9e4b514.png)

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- (특이 사항 1)
- (특이 사항 2)

2021-11-27 17:12 UTC, yuchanleeme requested changes

2021-11-27 17:12 UTC, yuchanleeme commented on client/src/api/groupHttpClient.ts
> +  public getOwnGroups = (): Promise<SimpleGroupCardData[]> => this.httpClient.get(`/own`);
이부분 /own/simple 로 바꿔야 할 것 같아요!!

2021-11-27 17:12 UTC, yuchanleeme commented on client/src/components/TextSwitchButton/index.tsx
> +  const leftClickHandler = () => {
핸들러 네이밍 컨벤션에 맞게 변경하면 좋을것 같아요!! `handleLeftButtonClick` 이런식으로 바꾸면 좋을것 같습니다!!

2021-11-27 17:12 UTC, yuchanleeme commented on client/src/components/TextSwitchButton/index.tsx
> +  const rightClickHandler = () => {
`handleRightButtonClick` 으로 바꾸면 좋을것 같아요!

2021-11-27 17:12 UTC, yuchanleeme commented on client/src/pages/MyGroupPage/SimpleGroupCardList/index.tsx
> +  background-color: #f6f8fa;
혹시 자주 쓰일것 같은 색상이면 theme 에 등록해서 사용해도 좋을것 같습니다!!

2021-11-27 17:12 UTC, yuchanleeme commented on client/src/components/TextSwitchButton/index.tsx
> +  background-color: ${(props) => (props.selected ? props.theme.Primary : '#fff')};
`#fff` 색상은 `props.theme.White`로 쓰는게 어떨까요??

2021-11-28 04:17 UTC, Donggggg requested changes

2021-11-28 04:17 UTC, Donggggg commented on client/src/components/TextSwitchButton/index.tsx
> +
`constants/enum`로 분리되야 할 것 같아유

2021-11-28 04:17 UTC, Donggggg commented on client/src/pages/MyGroupPage/SimpleGroupCard/index.tsx
> +      notify('아직 가입되지 않은 그룹이에요ㅠㅠ', ToastMessageEnum.ERROR);
`constants/consts`로 분리되야 할 것 같아요.

2021-11-28 04:36 UTC, who-is-hu commented on client/src/pages/MyGroupPage/SimpleGroupCardList/index.tsx
> +  background-color: #f6f8fa;
요기만 쓸것같아요!

2021-11-28 04:41 UTC, Donggggg approved these changes

2021-11-28 04:47 UTC, yuchanleeme approved these changes
확인했습니다!! 수고하셨어요~~👍

2021-11-28 04:49 UTC, merged