[FE] refactoirng 후 생긴 버그 수정
boostcampwm-2021/web32-SSUL pull request #218
Opened 2021-11-29 13:16 UTC by yuchanleeme

## 관련 이슈

- closes #175 
## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무
- [ ] test 통과 여부

## 작업 요약
> 작업 내역 요약

버그 수정

## Preview

> 선택 사항

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- (특이 사항 1)
- (특이 사항 2)

2021-11-29 16:09 UTC, Donggggg requested changes

2021-11-29 16:09 UTC, Donggggg commented on client/src/pages/GroupRecruitPage/GroupCardList.tsx
>    grid-template-rows: repeat(auo-fit, minmax(100px, 2fr));
`auo-fit`은 오타같습니다..?!

2021-11-29 16:09 UTC, Donggggg commented on client/src/pages/GroupRecruitPage/index.tsx
> +          <FloatingButton to={{ pathname: `/group/create` }}>
`!!id`로 처리해주신 이유가 궁금합니다!

2021-11-29 16:09 UTC, Donggggg commented on server/src/domains/group/service/GroupService.ts
> +    console.log(enrollmentType);
log가 남아있는 것 같아요..!

2021-11-29 16:09 UTC, Donggggg commented on server/src/domains/group/service/GroupService.ts
> +    console.log('apply', applyInfo);
log가 남아있는 것 같아요..!

2021-11-30 02:16 UTC, who-is-hu approved these changes

2021-11-30 04:11 UTC, yuchanleeme commented on client/src/pages/GroupRecruitPage/index.tsx
> +          <FloatingButton to={{ pathname: `/group/create` }}>
!id로만 처리하니까 0이라는 숫자가 렌더링이 되더라고요.. 그래서 따로 loding State로 관리하려했는데 너무 코드가 길어질거 같아서 다른방법을 생각했습니다. 그러다 !! 두번 붙이니까 !0 이런느낌으로 처리돼서 출력이 안되길래 저렇게 작성했습니다!!

2021-11-30 04:12 UTC, yuchanleeme commented on server/src/domains/group/service/GroupService.ts
> +    console.log(enrollmentType);
헉... 콘솔로그들이 안빠졌었네요 수정하겠습니다!!

2021-11-30 05:03 UTC, Donggggg commented on client/src/pages/GroupRecruitPage/index.tsx
> +          <FloatingButton to={{ pathname: `/group/create` }}>
아하 이해했습니다! 그러네요..ㅎ

2021-11-30 05:05 UTC, Donggggg approved these changes
여유롭지 않으셨을 텐데 빠른 수정 감사합니다!
고생하셨어유

2021-11-30 05:46 UTC, merged