[FE] 멘토 모집 페이지/ 페이지네이션 수정
boostcampwm-2021/web32-SSUL pull request #238
Opened 2021-12-01 18:00 UTC by yuchanleeme

## 관련 이슈

- closes #237 

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무
- [ ] test 통과 여부

## 작업 요약
> 작업 내역 요약

멘토 모집 페이지, 페이지네이션 관련 사항 수정

## Preview

> 선택 사항

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 애니메이션 효과로 로딩을 처리했습니다. preview에 담을라고 했는데 캡처가 프레임을 못따라가서 담기지 못했습니다..
- 목록을 불러오는 중 ... <- 이 ... 이 애니메이션 처리가 됩니다.

2021-12-01 18:13 UTC, Donggggg requested changes

2021-12-01 18:13 UTC, Donggggg commented on client/src/components/Pagination/index.tsx
> +import RightButton from '@assets/right_button.png';
이미지 파일 네이밍 컨벤션에 맞지 않는 것 같아요.!
`icon_arrow_left.png` 나 `btn_arrow_right.png`가 좋을 것 같아요.

2021-12-01 18:13 UTC, Donggggg commented on client/src/pages/MentorRecruitPage/MentorModal/GroupList.tsx
> +          <LoadingText>목록 불러오는 중</LoadingText>
constants로 분리해야할 메시지 같습니다!

2021-12-01 18:13 UTC, Donggggg commented on client/src/pages/MentorRecruitPage/MentorModal/GroupList.tsx
> +`;
오 이렇게 쉽게 `...`을 처리할 수 있군요..!

2021-12-02 06:30 UTC, Donggggg approved these changes

2021-12-02 07:08 UTC, ChanYangYu approved these changes

2021-12-02 07:08 UTC, merged