[FE]모집페이지 - 기술스택 목록 필터 박스
boostcampwm-2021/web32-SSUL pull request #45
Opened 2021-11-03 17:27 UTC by yuchanleeme

## 관련 이슈

- closes #16

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무

## 작업 요약
> 작업 내역 요약
* 기술스택 목록 필터 박스 기능 구현

## Preview

> 선택 사항

![기술스택 목록](https://user-images.githubusercontent.com/48426909/140154004-be38f29e-763b-4d3b-a18b-638ab45fcc37.gif)

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 기술 스택 일정 개수 이상 클릭 시 shake 애니메이션 효과를 줬습니다.
- 애니메이션 구현 과정에서 여러번 클릭 하면 적용이 안되는 이슈가 있었습니다.  `clickedTechStack.offsetWidth;` 이 코드 하나 더 추가해서 작동시켰는데 이게 맞는지 모르겠습니다..
- 웹이라는 특성상 선택된 기술스택을 스크롤해서 보여주는건 좀 아닌거 같아서 일단 개수를 제한시켜서 작동하게 해놓았습니다.
- redux를 기본적으로 적용해서 다뤘습니다. -> 이 부분은 내일 만나서 정확하게 구조를 확정짓고 하면 좋을 것 같습니다.

2021-11-04 07:36 UTC, who-is-hu requested changes

2021-11-04 07:36 UTC, who-is-hu commented on client/src/api/techStack/index.ts
> +export const getTechStackList = (): Promise<TechStack[]> => requests.get(`/TechStack`);
이거 /techstack 이여야 할 것같슴다.

2021-11-04 07:52 UTC, yuchanleeme commented on client/src/api/techStack/index.ts
> +export const getTechStackList = (): Promise<TechStack[]> => requests.get(`/TechStack`);
넵! 해결했습니다.

2021-11-04 07:53 UTC, who-is-hu approved these changes

2021-11-04 07:53 UTC, Donggggg approved these changes

2021-11-04 07:53 UTC, Donggggg commented on client/src/api/techStack/index.ts
> +};
axios를 라이브러리화한 부분인 것 같은데 도메인 쪽에 추상화가 되는게 아니라 api 폴더의 루트에 추상화되면 좋을 것 같아요 🙂

2021-11-04 07:53 UTC, Donggggg commented on client/src/components/SearchFilter/SearchFilterTechSection/SelectedTechList.tsx
> +  };
이벤트 핸들러의 이벤트 인자를 any 타입으로 달아주셨는데 React.MouseEvent<HTMLButtonElement>로 변경하면 타입을 명시할 수 있을 것 같아요!

2021-11-04 07:53 UTC, Donggggg commented on client/src/components/SearchFilter/SearchFilterTechSection/TechList.tsx
> +    clickedTechStack.offsetWidth;
23번 라인이 필요한 이유가 뭘까요?!

2021-11-04 07:54 UTC, merged

2021-11-05 15:40 UTC, yuchanleeme commented on client/src/api/techStack/index.ts
> +};
이부분 추상화 코드 만들어주셔서 감사합니다! #53

2021-11-05 15:40 UTC, yuchanleeme commented on client/src/components/SearchFilter/SearchFilterTechSection/SelectedTechList.tsx
> +  };
넵넵!! 수정하겠습니다.

2021-11-05 15:43 UTC, yuchanleeme commented on client/src/components/SearchFilter/SearchFilterTechSection/TechList.tsx
> +    clickedTechStack.offsetWidth;
애니메이션 재사용을 위해서 해당 코드를 넣었습니다! 클래스를 지워주는 코드는 브라우저가 코스트가 많이 든다고 판단해 lazy하게 렌더링을 한다고 해서 강제로 offsetWidth를 호출하여 애니메이션을 재 실행시키게 했습니다!