[BE]인증 - Github OAuth 로그인(상)
boostcampwm-2021/web32-SSUL pull request #53
Opened 2021-11-05 14:57 UTC by Donggggg

## 관련 이슈

- #26

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [x] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무

## 작업 요약
> 작업 내역 요약
- Github OAuth 앱 등록  
- Github OAuth 클라이언트단 구현  
- Github OAuth 서버단 구현  
  - 컨트롤러, 서비스, 세션 처리
- loader의 server 로직 순서 변경

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 우선.. 해당 이슈는 분량이 너무 많아 2개의 PR로 분리하겠습니다..;;ㅠ
- 추가 태스크는 다음과 같습니다. 
> 1. [BE]회원가입 로직 
> 2. [BE]유저 insert 
> 3. [BE] 세션DB 추가 
> 4. [FE] 클라이언트 세션 유지 
> 5. [FE] 클라이언트 slient-refresh

- 세션을 처리하던 중 서버 loader의 server 로직이 controller보다 뒤에서 실행되어 express 미들웨어가 정상적으로 작동하지 않는 버그를 발견했고, server 로직의 위치를 수정해 버그를 해결했습니다.

2021-11-05 15:32 UTC, Donggggg commented on server/src/domains/auth/api/AuthContorller.ts
> +    if (!githubId) session.githubId = githubUserData.githubId;
세션 관련 로직이 Controller에 들어가는게 맞을까요?

2021-11-05 15:32 UTC, Donggggg commented on server/src/loader/express.ts
세션 config 코드가 해당 파일에 위치하는게 맞을까요??

2021-11-05 15:34 UTC, who-is-hu commented on server/src/domains/auth/api/AuthContorller.ts
> +    if (!githubId) session.githubId = githubUserData.githubId;
세션은 서비스에 들고가지 않아서 저두 이렇게 합니다.

2021-11-05 15:36 UTC, who-is-hu commented on server/src/loader/express.ts
config 폴더에 있는게 좋긴한데 우선 process.env 에 접근하는 것들만 기존에 config/index.ts 에서 가져와서 config를 통해 사용하게 끔 고치면 좋을것같네요

2021-11-05 15:37 UTC, who-is-hu requested changes
위에언급한 process.env 만 처리 부탁!

근데 loader 쪽에서 순서에 무관할 것 같은데 어떤 에러였나요?

2021-11-05 15:40 UTC, who-is-hu commented on server/src/loader/express.ts
그리고 굳이 sessionConfig가 굳이 전역에 위치하지 않아도 될듯합니다.

2021-11-05 15:47 UTC, Donggggg commented
@who-is-hu 
use함수로 미들웨어를 등록할 때 라우터를 먼저 등록하고 그 외 미들웨어를 후에 등록하면 
라우터에서 그 외 미들웨어들이 동작하지 않아서 문제였습니다 !..

제 상황에선 router -> session 가 문제였고 session -> router가 되도록 순서를 바로 잡았습니다.

2021-11-05 15:49 UTC, yuchanleeme commented on client/src/api/index.ts
> +};
http header 부분도 추상화할때 같이 넣는것도 좋은 것 같습니다!

2021-11-05 15:52 UTC, yuchanleeme approved these changes
- 코멘트한 부분 이외에는 문제 없다고 생각합니다!
- api 추상화를 해서 프로젝트 코드들이 조금 깔끔해지겠네요!! 수고하셨습니다~~

2021-11-05 15:59 UTC, ChanYangYu approved these changes
axios 코드 이해했고 api코드 작성시 참고해서 작성하겠습니다!

2021-11-06 08:55 UTC, who-is-hu approved these changes

2021-11-06 08:56 UTC, merged