[BE]모집페이지 - 필터링 그룹 검색 API
boostcampwm-2021/web32-SSUL pull request #90
Opened 2021-11-10 10:48 UTC by yuchanleeme

## 관련 이슈

- closes #88 

## 셀프 체크리스트

> 최소 1명 이상의 assign을 받아야만 Merge 가능합니다.

- [ ] Warning Message 발생 유/무
- [x] Coding Convention 준수 유/무

## 작업 요약
> 작업 내역 요약

필터링 된 정보를 기반으로 그룹 검색 할 수 있는 API를 만들었습니다.

## Preview

> 선택 사항

## PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점
> 백로그에 없지만 필요하여 구현한 기능 

- 쿼리문으로 정보를 가져온 다음 각각 해결하는 방식을 사용했습니다.
- postman으로 여러 url로 테스트 결과 문제 없었습니다.

2021-11-10 10:51 UTC, ChanYangYu commented on server/src/domains/category/repository/CategoryRepository.ts
> +      .where('category.name = :name', { name })
`'category.name = :name', { name }` 이렇게도 할 수 있군요! 엄청 깔끔하네요!

2021-11-10 10:59 UTC, ChanYangYu approved these changes
👍👍 복잡한 쿼리로직이 많이 보였는데 많은 생각을 하고 구현하신게 보이네요! 고생하셨습니다 유찬님!

2021-11-10 10:59 UTC, ChanYangYu commented on server/src/domains/group/service/GroupService.ts
> +import { Group } from '../models/Group';
앗 이부분 제가 prettier 적용을 못했던 부분같네요.. 잡아주셔서 감사합니다 유찬님!

2021-11-10 11:32 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +    @QueryParam('category') category: string,
id로 하는게 좋지않을까요?

2021-11-10 11:33 UTC, who-is-hu commented on server/src/domains/category/repository/CategoryRepository.ts
> +  }
이렇게 간단한거는 쿼리빌더보다 typeorm에서 제공하는 기능쓰는게 더 좋을 것 같아요

2021-11-10 11:38 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +    const groups: Group[] = await this.groupService.getGroups(name, category);
category 뿐만 아니라 query 요소들도 
where 절에 들어가 db에서 가저오는 시점부터 필터링 되는게 좋을 것 같습니다.
이렇게 되면 결국 DB에선 카테고리만 뺴고 모든 IO가 발생합니당.

2021-11-10 11:39 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +  addOtherGroupInfo(groups: Group[], filterdTechStack: string[]) {
여기 있기보단 위에 언급한것처럼 db에서 처음부터 필터링되서 오게끔 하는게 좋을 것 같습니다.

2021-11-10 11:48 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +    const addedOtherGroupInfo = await this.addOtherGroupInfo(groups, filterdTechStack);
db에서 쿼리하는 시점에서 where문으로 필터링 되는게 더 좋을 것 같습니당.
동적으로 where문 추가 할 수 있게끔요
이렇게되면 카테고리랑 이름 뺴곤 IO가 다 생길거라고 생각합니다.
Spring에선 Specification이나 Creteria를 사용하는데 참고해보심 될것 같습니다.

2021-11-10 11:48 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +  addOtherGroupInfo(groups: Group[], filterdTechStack: string[]) {
위에 언급한것처럼 repository 단에서 해결되야할 문제 같습니다.

2021-11-10 11:50 UTC, who-is-hu commented on server/src/domains/group/service/GroupService.ts
> +  public async getGroups(name: string = '', category: string = '') {
함수 시그니쳐만 봐선 전부가져오는 것 같은데
카테고리랑 이름 필터링이있어서 헷갈릴수있을것 같습니다.

2021-11-10 11:51 UTC, who-is-hu commented on server/src/domains/user/repository/ProfileRepository.ts
> +      .select([
join 한번정도의 복잡도면 쿼리빌더를 안쓰는것도 괜찮지 않을까요

2021-11-10 11:56 UTC, who-is-hu requested changes
아 글구 Pagination 필요합니다.

2021-11-10 11:58 UTC, Donggggg commented on server/src/domains/group/api/GroupController.ts
> +    return addedOtherGroupInfo.filter((item) => item);
여기서 item에 최종 정보가 다들어간 객체가 들어가는 것으로 추정은 되는데 왜 한 번 더 필터링을 하는 건가요?!
`item => item`의 표현식이 직관적이지 않은 것 같습니다!

2021-11-11 13:56 UTC, yuchanleeme commented on server/src/domains/user/repository/ProfileRepository.ts
> +      .select([
반영했습니다!

2021-11-11 13:56 UTC, yuchanleeme commented on server/src/domains/group/service/GroupService.ts
> +  public async getGroups(name: string = '', category: string = '') {
이름 수정했습니다!!

2021-11-11 13:56 UTC, yuchanleeme commented on server/src/domains/group/api/GroupController.ts
> +  addOtherGroupInfo(groups: Group[], filterdTechStack: string[]) {
repository단으로 분리했습니다!

2021-11-11 13:57 UTC, yuchanleeme commented on server/src/domains/group/api/GroupController.ts
> +    const addedOtherGroupInfo = await this.addOtherGroupInfo(groups, filterdTechStack);
이 부분에 대해서는 조금 더 고심해 볼 필요가 있을 것 같습니다!! 회의에서 서로 토론하는걸로 해용!!

2021-11-11 13:57 UTC, yuchanleeme commented on server/src/domains/category/repository/CategoryRepository.ts
> +  }
제거했습니다!!

2021-11-11 13:57 UTC, yuchanleeme commented on server/src/domains/group/api/GroupController.ts
> +    @QueryParam('category') category: string,
id로 변경했습니다~~

2021-11-11 13:57 UTC, yuchanleeme commented on server/src/domains/group/api/GroupController.ts
> +    return addedOtherGroupInfo.filter((item) => item);
직관적이게 변경했습니다!!

2021-11-11 13:58 UTC, yuchanleeme commented
> 아 글구 Pagination 필요합니다.

따로 이슈로 빼서 관리하겠습니다!!

2021-11-11 14:03 UTC, who-is-hu commented on server/src/domains/group/api/GroupController.ts
> +    const addedOtherGroupInfo = await this.addOtherGroupInfo(groups, filterdTechStack);
냅 해결하기 복잡한 문제네요 따로 이슈로 만들고 개선과정을 남기는 방식으로 합시당

2021-11-11 14:03 UTC, who-is-hu approved these changes

2021-11-11 14:03 UTC, merged